# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-11-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Fecha de publicación'),
        ),
    ]
